import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { registerLicense } from '@syncfusion/ej2-base';

// Registering Syncfusion license key
registerLicense('Mgo+DSMBaFt+QHFqVkNrWE5FdEBAXWFKblJ2T2FbdV14ZDU7a15RRnVfQV9nSH1RdEBlX35acQ==;Mgo+DSMBPh8sVXJ1S0d+X1RPckBDX3xLflF1VWJZdVxyflZOcDwsT3RfQF5jSnxXd0ZhW3pYdnZcRw==;ORg4AjUWIQA/Gnt2VFhhQlJBfVtdXGFWfFN0RnNYf1Rydl9FaEwxOX1dQl9gSX1RckRgW31bdnJRT2E=;MTQ1NDc3OEAzMjMxMmUzMTJlMzMzNWhCUDhjTmpUNUlhQSsyc0VFQXFRMENjZjV0dno4WjUrL1VhQkpQOHRnSjQ9;MTQ1NDc3OUAzMjMxMmUzMTJlMzMzNUVET3AxSndTVHNKbHllemhQN0lkdlNQeURrN25YMkswM2tjQWhvMk0xeTg9;NRAiBiAaIQQuGjN/V0d+XU9Hc1RGQmJLYVF2R2BJfl56dldMY1RBJAtUQF1hSn5QdEFiWn1cdXJSR2dd;MTQ1NDc4MUAzMjMxMmUzMTJlMzMzNWUreEVlSnc0ZkJ1Ky8vMlAyc082VFNLTDFQaC9mc3ZQODk5UFRiRzNJem89;MTQ1NDc4MkAzMjMxMmUzMTJlMzMzNVVVSWc4VG5NMk40Z0RXN2dWWmE1WEdwTms3NnB6M01hYVdYampkMEliNEk9;Mgo+DSMBMAY9C3t2VFhhQlJBfVtdXGFWfFN0RnNYf1Rydl9FaEwxOX1dQl9gSX1RckRgW31bdnNSQ2E=;MTQ1NDc4NEAzMjMxMmUzMTJlMzMzNVIrak8yNngvWm9MaUFMb0poUUx3SzdHTFlrWjdqUDFrcDdIaHBLeHhSYTQ9;MTQ1NDc4NUAzMjMxMmUzMTJlMzMzNUd0QjdWbjM5bEZPSzVidXprMXFqK0tqODZvYi81OUh5aHFBK2tQL004Rk09;MTQ1NDc4NkAzMjMxMmUzMTJlMzMzNWUreEVlSnc0ZkJ1Ky8vMlAyc082VFNLTDFQaC9mc3ZQODk5UFRiRzNJem89');

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
